### ISSUE TITLE
What is the Issuer Private Key?

### ISSUE THREAD

**Issue by paulayo93** [therealharpaljadeja/socialconnect_rn_demo#1]
How do I get the **ISSUER_PRIVATE_KEY=**?

<img width="1303" alt="Screenshot 2023-02-16 at 14 00 45" src="https://user-images.githubusercontent.com/52790286/219372043-cd664298-b994-49de-b57c-883de5ef369b.png">

Thanks in advance for the help.

**Comment by therealharpaljadeja** [comment]
That's upto you, I mean the private key you put there becomes the `Issuer`

**Comment by paulayo93** [comment]
Oh Alright, I understand now.

Thanks @therealharpaljadeja
